export {default as acura} from "./acura.svg"
export {default as alfaRomeo} from "./alfa romeo.svg"
export {default as alfaRomeoAlt} from "./alfa romeo alt.svg"
export {default as amGeneral} from "./am general.svg"
// export {default as astonMartin} from "./aston martin.svg"
// export {default as astonMartinAlt} from "./aston martin alt.svg"
export {default as audi} from "./audi.svg"
export {default as bentley} from "./bentley.svg"
export {default as bmw} from "./bmw.svg"
export {default as bugatti} from "./bugatti.svg"
export {default as buick} from "./buick.svg"
export {default as cadillac} from "./cadillac.svg"
export {default as chevrolet} from "./chevrolet.svg"
export {default as chrysler} from "./chrysler.svg"
export {default as citroen} from "./citroen.svg"
export {default as dacia} from "./dacia.svg"
export {default as daewoo} from "./daewoo.svg"
// export {default as default} from "./default.svg"
export {default as dodge} from "./dodge.svg"
export {default as eagle} from "./eagle.svg"
export {default as ferrari} from "./ferrari.svg"
export {default as fiat} from "./fiat.svg"
export {default as fiatAlt} from "./fiat alt.svg"
export {default as fisker} from "./fisker.svg"
export {default as ford} from "./ford.svg"
export {default as genesis} from "./genesis.svg"
export {default as geo} from "./geo.svg"
export {default as gmc} from "./gmc.svg"
export {default as honda} from "./honda.svg"
export {default as hummer} from "./hummer.svg"
export {default as hyundai} from "./hyundai.svg"
export {default as infiniti} from "./infiniti.svg"
export {default as isuzu} from "./isuzu.svg"
export {default as jaguar} from "./jaguar.svg"
export {default as jaguarAlt} from "./jaguar alt.svg"
export {default as jeep} from "./jeep.svg"
export {default as jeepAlt} from "./jeep alt.svg"
export {default as kia} from "./kia.svg"
export {default as lamborghini} from "./lamborghini.svg"
export {default as lamborghiniAlt} from "./lamborghini alt.svg"
export {default as landRover} from "./land rover.svg"
export {default as lexus} from "./lexus.svg"
export {default as lincoln} from "./lincoln.svg"
export {default as lotus} from "./lotus.svg"
export {default as lotusAlt} from "./lotus alt.svg"
export {default as maserati} from "./maserati.svg"
export {default as maybach} from "./maybach.svg"
export {default as mazda} from "./mazda.svg"
export {default as mazdaAlt} from "./mazda alt.svg"
export {default as mclaren} from "./mclaren.svg"
export {default as mclarenAlt} from "./mclaren alt.svg"
export {default as mercedesBenz} from "./mercedes benz.svg"
export {default as mercedesBenzAlt} from "./mercedes benz alt.svg"
export {default as mercury} from "./mercury.svg"
export {default as mini} from "./mini.svg"
export {default as miniAlt} from "./mini alt.svg"
export {default as mitsubishi} from "./mitsubishi.svg"
export {default as nissan} from "./nissan.svg"
export {default as oldsmobile} from "./oldsmobile.svg"
export {default as opel} from "./opel.svg"
export {default as panoz} from "./panoz.svg"
export {default as peugeot} from "./peugeot.svg"
// export {default as peugeotAlt} from "./peugeot alt.svg"
export {default as plymouth} from "./plymouth.svg"
// export {default as pontiac} from "./pontiac.svg"
export {default as porsche} from "./porsche.svg"
export {default as ram} from "./ram.svg"
export {default as ramAlt} from "./ram alt.svg"
export {default as renault} from "./renault.svg"
// export {default as renaultAlt} from "./renault alt.svg"
export {default as rollsRoyce} from "./rolls royce.svg"
export {default as saab} from "./saab.svg"
export {default as saabAlt} from "./saab alt.svg"
export {default as saturn} from "./saturn.svg"
export {default as scion} from "./scion.svg"
export {default as seat} from "./seat.svg"
export {default as skoda} from "./skoda.svg"
export {default as smart} from "./smart.svg"
export {default as spyker} from "./spyker.svg"
export {default as spykerAlt} from "./spyker alt.svg"
export {default as subaru} from "./subaru.svg"
export {default as subaruAlt} from "./subaru alt.svg"
// export {default as suzuki} from "./suzuki.svg"
export {default as tesla} from "./tesla.svg"
export {default as toyota} from "./toyota.svg"
export {default as volkswagen} from "./volkswagen.svg"
export {default as volvo} from "./volvo.svg"
export {default as volvoAlt} from "./volvo alt.svg"