export { default as AboutUs } from "./aboutUs/AboutUs";
export { default as Faq } from "./faq/Faq";
export { default as Home } from "./home/Home";
export { default as ProductList } from "./productList/ProductList";
export { default as Product } from "./product/Product";
export { default as AddProduct } from "./addProduct/AddProduct";
export { default as ShopList } from "./shopList/ShopList";
export { default as Shop } from "./shop/Shop";
export { default as ShAuthop } from "./auth/Auth";
